name: DeltaEssentials
main: com.yahoo.tracebachi.DeltaEssentials.DeltaEssentialsPlugin
version: 1.3
author: Trace Bachi (tracebachi@yahoo.com, BigBossZee)
depend: [DeltaRedis, Essentials, Herochat]
commands:
  moveto:
    description: Sends players to different servers.
    aliases: [mt]
  tell:
    description: Sends a message to another player.
    aliases: [t, tell, pm, m, msg]
  reply:
    description: Sends a message to another player as a reply.
    aliases: [r]
  socialspy:
    description: Shows a copy of all private messages on the server when enabled.
    aliases: [spy]
  tp:
    description: Teleports players.
    aliases: [detp]
  tphere:
    description: Teleports other to self.
    aliases: [detphere]
  tpahere:
    description: Sends teleport request.
    aliases: [detpahere]
  tpaccept:
    description: Accepts teleport request.
    aliases: [detpaccept]
  tptoggle:
    description: Controls if players can teleport to the player.
    aliases: [detptoggle]
  kick:
    description: Kicks the player from the server.
    aliases: [dekick]
  jail:
    description: Sends a player to the jail server and jails them.
    aliases: [dejail]
  joinstop:
    description: Blocks all players from joining the server when enabled. Useful for shutdowns to prevent players from rejoining.
    aliases: [js]

permissions:
  DeltaEss.Tell.Use:
    description: Use /tell and /reply
  DeltaEss.Tell.Color:
    description: Lets players use color codes in their messages.
  DeltaEss.MoveTo.Self:
    description: Allows the player to switch servers.
  DeltaEss.MoveTo.Other:
    description: Allows the player to force others to switch servers.
  DeltaEss.MoveTo.Bypass:
      description: Allows the player to bypass blocked servers.
  DeltaEss.Tp.Self:
    description: Teleports self to another player.
  DeltaEss.Tp.Other:
    description: Teleports player to another player.
  DeltaEss.Tp.Alert:
    description: Sends a message to the player when another player teleports to them.
  DeltaEss.Tp.IgnoreVanish:
    description: Allows the player to teleport to another even if the other player is vanished.
  DeltaEss.Tpa.Send:
    description: Sends a teleport request to another.
  DeltaEss.Tpa.Accept:
    description: Accepts a teleport request.
  DeltaEss.TpToggle.Use:
    description: Accepts a teleport request.
  DeltaEss.TpToggle.Bypass:
    description: Accepts a teleport request.
  DeltaEss.Kick:
    description: Allows the player to kick others.
  DeltaEss.Jail:
    description: Allows the player to jail others.
  DeltaEss.SocialSpy:
    description: Allows the player to listen to messages on the server.
  DeltaEss.JoinStop:
    description: Allows the player to use the stopjoin command.
