ownerName: DeltaEssentials
main: com.gmail.tracebachi.DeltaEssentials.DeltaEssentials
version: ${project.version}
author: Trace Bachi (tracebachi@gmail.com, BigBossZee)
depend: [DeltaRedis, DeltaExecutor]
commands:
  deltaessentials:
    aliases: [deltaess, de]
  disposal:
    aliases: [trash]
  dvanish:
    aliases: [dv]
  lockdown:
    aliases: []
  moveall:
    aliases: []
  moveto:
    aliases: [mt]
  socialspy:
    aliases: [spy]
  tell:
    aliases: [t, m, msg, pm]
  reply:
    aliases: [r]
  tp:
    aliases: [detp]
  tpaccept:
    aliases: [detpaccept]
  tpahere:
    aliases: [detpahere]
  tpdeny:
    aliases: [detpdeny]
  tphere:
    aliases: [detphere]
